# Generated by Django 5.0.14 on 2026-03-09 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_chat_type_chatsession_direct_pair_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='chat.chatsession')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_chat_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_chat_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chat_session', 'inviter', 'invitee')},
            },
        ),
    ]
