# Generated by Django 5.0.14 on 2026-03-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('group', 'Group'), ('direct', 'Direct')], default='group', max_length=16),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='direct_pair_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
