# Generated by Django 5.0.14 on 2026-03-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
