# Generated by Django 5.0.14 on 2026-03-18 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatsessionmessage',
            index=models.Index(fields=['chat_session', 'create_date'], name='idx_msg_room_created_at'),
        ),
    ]
